### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory.     PortAudioSharp.PortAudio.Pa_OpenStream()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tlove123/portaudiosharp#7]
```
What steps will reproduce the problem?

1. compile portaudio with asio as indicated in 
http://portaudio.com/docs/v19-doxydocs/compile_windows.html
   * extract portaudio archive
   * extract asio sdk into asio hostapi subfolder and rename src\hostapi\asio\ASIOSDK2 (asio sdk archive) to src\hostapi\asio\ASIOSDK
   * open msvc solution found in build\msvc and set switches for all platforms as indicated in URL above. leaving the structure aligning to default
2. "compile" or assemble portaudiosharp
3. place portaudio_x64.dll, renamed to portaudio.dll in 
\PortAudioSharpTest\bin\Debug


What is the expected output? What do you see instead?

I don't know what to expect, certainly not the error below.


What version of the product are you using? On what operating system?

windows 7 64bit


Please provide any additional information below.

I changed the code just a little bit to show the pointer types, so that the   
errorCheck("OpenDefaultStream", PortAudio.Pa_OpenStream( ... )) call appears in 
line 150.

PortAudioSharpTest.exe

PortAudioSharp Test
*******************

PortAudioSharpTest version: 0.1.4419.2504
PortAudioSharp version: 0.19.3.2504
PortAudio version: PortAudio V19-devel (built Feb  6 2012 01:33:54) (1899)

PortAudio: Initializing...

before paHostApiInitializers[0].
after paHostApiInitializers[0].
before paHostApiInitializers[1].
ASIO names[0]:Audio 8 DJ
after paHostApiInitializers[1].
before paHostApiInitializers[2].
WASAPI: device idx: 00
WASAPI: ---------------
WASAPI:0| name[Speakers (SoundMAX Integrated Digital HD Audio)]
WASAPI:0| form-factor[1]
WASAPI:0| def.SR[48000] max.CH[2] latency{hi[0.010000] lo[0.003000]}
WASAPI: device idx: 01
WASAPI: ---------------
WASAPI:1| name[SPDIF Interface (SoundMAX Integrated Digital HD Audio)]
WASAPI:1| form-factor[8]
WASAPI:1| def.SR[44100] max.CH[2] latency{hi[0.010159] lo[0.003000]}
WASAPI: device idx: 02
WASAPI: ---------------
WASAPI:2| name[Microphone (SoundMAX Integrated Digital HD Audio)]
WASAPI:2| form-factor[4]
WASAPI:2| def.SR[48000] max.CH[2] latency{hi[0.010000] lo[0.003000]}
WASAPI: initialized ok
after paHostApiInitializers[2].
before paHostApiInitializers[3].
Setup called
Enum called
noError = 0
Enum called
noError = 1
Device 1 has render alias
Enum called
noError = 0
Enum called
noError = 0
Device 3 has capture alias
Enum called
noError = 0
Enum called
noError = 1
Device 5 has render alias
Enum called
Interfaces found: 3
Device 1 has render alias
Interface 1, Name: HD Audio digital out
Creating pin 0:
No standard streaming
Creating pin 1:
Not source/sink
Filter NOT created
Device 3 has capture alias
Interface 3, Name: SoundMAX HD Audio I
Creating pin 0:
No standard streaming
Creating pin 1:
Not source/sink
Filter NOT created
Device 5 has render alias
Interface 5, Name: SoundMAX HD Audio O
Creating pin 0:
No standard streaming
Creating pin 1:
Not source/sink
Filter NOT created
after paHostApiInitializers[3].
PortAudio: Initialize OK

PortAudio: available API index: 0
[PaHostApiInfo]
structVersion: 1
type: paMME
name: MME
deviceCount: 5
defaultInputDevice: 1
defaultOutputDevice: 3

PortAudio: available API index: 1
[PaHostApiInfo]
structVersion: 1
type: paASIO
name: ASIO
deviceCount: 0
defaultInputDevice: -1
defaultOutputDevice: -1

PortAudio: available API index: 2
[PaHostApiInfo]
structVersion: 1
type: paWASAPI
name: Windows WASAPI
deviceCount: 3
defaultInputDevice: 7
defaultOutputDevice: 5

PortAudio: available API index: 3
[PaHostApiInfo]
structVersion: 1
type: paWDMKS
name: Windows WDM-KS
deviceCount: 0
defaultInputDevice: -1
defaultOutputDevice: -1

PortAudio: selected Host API: 0

PortAudio: input device:
[PaDeviceInfo]
name:
hostApi: 2
maxInputChannels: 0
maxOutputChannels: 1889785610
defaultLowInputLatency: 0,09
defaultLowOutputLatency: 0,18
defaultHighInputLatency: 0,18
defaultHighOutputLatency: 44100
defaultSampleRate: 5,4535343634296E-312

PortAudio: output device:
[PaDeviceInfo]
name:
hostApi: 0
maxInputChannels: 2
maxOutputChannels: 1889785610
defaultLowInputLatency: 0,09
defaultLowOutputLatency: 0,18
defaultHighInputLatency: 0,18
defaultHighOutputLatency: 44100
defaultSampleRate: 5,4535343634296E-312

PortAudio: Starting...

PortAudio:   data ptr = 0
stream ptr = 0

System.AccessViolationException: Attempted to read or write protected memory. 
This is often an indication that other memory is corrupt.
   at PortAudioSharp.PortAudio.Pa_OpenStream(IntPtr& stream, PaStreamParameters& inputParameters, PaStreamParameters& outputParameters, Double sampleR
ate, UInt32 framesPerBuffer, PaStreamFlags streamFlags, 
PaStreamCallbackDelegate streamCallback, IntPtr userData)
   at PortAudioSharp.Audio.streamOpen(Int32 inputDevice, Int32 inputChannels, Int32 outputDevice, Int32 outputChannels, Int32 sampleRate, UInt32 framesPerBuffer) in D:\Users\alex\Downloads\PortAudioSharp-src-0.19.3\PortAudioSharp-src-0.19.3\PortAudioSharp\src\PortAudioSharp\Audio.cs:line 150
   at PortAudioSharp.Audio.Start() in D:\Users\alex\Downloads\PortAudioSharp-src-0.19.3\PortAudioSharp-src-0.19.3\PortAudioSharp\src\PortAudioSharp\Audio.cs:line 80
   at PortAudioSharpTest.PortAudioTest.Run() in D:\Users\alex\Downloads\PortAudioSharp-src-0.19.3\PortAudioSharp-src-0.19.3\PortAudioSharpTest\src\PortAudioTest.cs:line 78
PortAudio: Terminating...

TerminateHostApis in
TerminateHostApis out
PortAudio: Terminate OK

```

Original issue reported on code.google.com by `lxbl...@gmail.com` on 6 Feb 2012 at 11:16

**Comment by GoogleCodeExporter** [comment]
```
I have never tested PortAudioSharp with the 64 bit version of the PortAudio 
dll, do you have the same problem with the 32 bit version?
```

Original comment by `R.Ger...@gmail.com` on 7 Feb 2012 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
hello again!

yes, the same problem occurred also with the 32bit dll.

BUT:   i tried to reproduce the problem and narrow it down to whether or not it 
is related to ASIO in the DLL. i started throwing out ASIO "stuff" including 
the sdk. so i basically assumed that the problem is on the portaudio side. 
turns out that the project became uncompilable and in the end the project had 
no C/C++ compiler references at all. it al seemed a bit strange. so i replaced 
the BUILD directory with the original one, converted it again to MSVC2010, 
configured as needed and compiled WITH ASIO again.

problem solved. -- error unreproducible.  I just don't know how that error 
could possibly have turned out. I don't get it.


thanks for the fast response!
```

Original comment by `lxbl...@gmail.com` on 7 Feb 2012 at 9:15

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the update.
I'm closing this issue, feel free to reopen it in case it's a reproducible 
error in PortAudioSharp.
```

Original comment by `R.Ger...@gmail.com` on 7 Feb 2012 at 9:30
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
you're welcome.

thank you for the incredible work in put in this project. so many benefit from 
your time invested. ;)
```

Original comment by `lxbl...@gmail.com` on 7 Feb 2012 at 9:55
